### Capstone 3: Breast Cancer Prediction

*Worldwide, breast cancer is the most common type of cancer in women and the second highest in terms of mortality rates.Diagnosis of breast cancer is performed when an abnormal lump is found (from self-examination or x-ray) or a tiny speck of calcium is seen (on an x-ray). After a suspicious lump is found, the doctor will conduct a diagnosis to determine whether it is cancerous and, if so, whether it has spread to other parts of the body.*

*This breast cancer dataset was obtained from the University of Wisconsin Hospitals, Madison from Dr. William H. Wolberg.*

**Goal**: Build a classification model that can accurately identify the diagnosis of breast cancer based on the measurements and attributes of a tumor.


*Source: https://www.kaggle.com/datasets/merishnasuwal/breast-cancer-prediction-dataset*

### Pre-processing

In [1]:
import pandas as pd
import numpy as np

from sklearn import __version__ as sklearn_version
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
#import breast cancer risk dataset
df = pd.read_csv('/Users/joyopsvig/github/springboard/3-Capstone/Notebooks/breastcancerrisk_cleaned.csv')

In [4]:
#view head of data
df.head()

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0
1,20.57,17.77,132.90,1326.0,0.08474,0
2,19.69,21.25,130.00,1203.0,0.10960,0
3,11.42,20.38,77.58,386.1,0.14250,0
4,20.29,14.34,135.10,1297.0,0.10030,0

In [5]:
#view info for data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568 entries, 0 to 567
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   mean_radius      568 non-null    float64
 1   mean_texture     568 non-null    float64
 2   mean_perimeter   568 non-null    float64
 3   mean_area        568 non-null    float64
 4   mean_smoothness  568 non-null    float64
 5   diagnosis        568 non-null    int64
dtypes: float64(5), int64(1)
memory usage: 26.8 KB

In [6]:
#view summary statistics
df.describe()

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,diagnosis
count,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000
mean,14.135847,19.300951,92.022694,655.604225,0.096242,0.626761
std,3.521236,4.296362,24.286633,351.810281,0.013792,0.484091
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.000000
25%,11.707500,16.177500,75.200000,420.300000,0.086290,0.000000
50%,13.375000,18.855000,86.290000,551.400000,0.095865,1.000000
75%,15.797500,21.802500,104.150000,784.150000,0.105300,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.144700,1.000000